// 本文件由 `cargo run -p xinqing-hub --bin export-bindings` 生成，请勿手改。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getStatus: () => typedError<StatusSnapshot, UiError>(__TAURI_INVOKE("get_status")),
	/**
	 *  状态解释（FR-STA-09）。不带 `mood_state_id` 时是当前显示状态的解释（还没切换过时为 `null`）；
	 *  带上时是看板时间线上那个状态点的解释，记录不存在或窗口已清理时为 `null`。
	 */
	stateExplain: (moodStateId: number | null) => typedError<{
	state: MoodState,
	/**
	 *  可能性百分比 0–100（快照里的 `prob` 是 0–1 小数，这里用整数百分比，名字上区分）；
	 *  只有本地规则或冷启动时为 `None`，界面不显示百分比。
	 */
	prob_pct: number | null,
	/**  最多 [`MAX_SIGNALS`] 条；为空时界面显示 `note.no_signal`。 */
	signals: Signal[],
	source: ExplainSource,
	/**  冷启动期间追加“还在熟悉你的习惯，判断可能不准”。 */
	cold_start: boolean,
} | null, UiError>(__TAURI_INVOKE("state_explain", { moodStateId })),
	/**
	 *  状态“准 / 不准”（FR-STA-07）。不带 `target_id` 时评价的是当前显示状态。
	 *  写入 `feedback` 表后，“不准”交给感知任务上调个人阈值；交不过去时（任务没运行或队列满）
	 *  也不报错，下次启动会从库里重放。还没有任何状态记录时什么也不做。
	 */
	submitFeedback: (target: FeedbackTarget, targetId: number | null, verdict: Verdict) => typedError<null, UiError>(__TAURI_INVOKE("submit_feedback", { target, targetId, verdict })),
	/**
	 *  主动报告心情（FR-STA-10）。写入 `self_report` 表后交给感知任务：之后 60 分钟显示用户说的状态
	 *  （“说不上来”不覆盖），并推送 `self_report:changed`。备注只存本地，用完即清零（NFR-PRI-09）。
	 */
	selfReportSet: (weather: SelfWeather, note: string | null) => typedError<null, UiError>(__TAURI_INVOKE("self_report_set", { weather, note })),
	/**  某天（本地日期 `YYYY-MM-DD`）的自评，按时间先后；看板时间线用实心标记显示。 */
	selfReportList: (date: string) => typedError<SelfReportItem[], UiError>(__TAURI_INVOKE("self_report_list", { date })),
	/**
	 *  重置基线（设置页“感知”分类，FR-SET-04、FR-STA-03 第 4 条）：清空个人统计值，
	 *  之后只用重置以后的窗口，重新进入冷启动（“正在熟悉你的打字习惯”从 0% 开始）。
	 */
	baselineReset: () => typedError<null, UiError>(__TAURI_INVOKE("baseline_reset")),
	/**  暂停 / 恢复感知（FR-WGT-06 右键菜单）：进行中的窗口作废，并经 XQP 下发给输入法（FR-SEN-06）。 */
	pauseSet: (on: boolean) => typedError<null, UiError>(__TAURI_INVOKE("pause_set", { on })),
	settingsGet: (key: string) => typedError<SettingValue, UiError>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: SettingValue) => typedError<null, UiError>(__TAURI_INVOKE("settings_set", { key, value })),
	consentGet: () => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_get")),
	/**  记录一项同意或撤回，返回更新后的全部同意状态，界面不用再读一次。 */
	consentSet: (item: ConsentItem, granted: boolean) => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_set", { item, granted })),
	/**  必须是 async：同步命令跑在主线程，在 Windows 上同步命令里建窗口会死锁（wry#583）。 */
	openWindow: (target: WindowTarget) => typedError<null, UiError>(__TAURI_INVOKE("open_window", { target })),
	/**
	 *  用户点了休息提醒卡片上的按钮（FR-RST-06 第 2 条）：完成或关闭后该类计时清零，“5 分钟后”顺延；
	 *  每次操作记一条 `reminder_log`（FR-RST-08）。服务没在运行时忽略。
	 */
	restAction: (kind: RestKind, action: RestAction) => typedError<null, UiError>(__TAURI_INVOKE("rest_action", { kind, action })),
	aiConfigGet: () => typedError<AiConfigView, UiError>(__TAURI_INVOKE("ai_config_get")),
	/**  保存 AI 服务地址与密钥（FR-AIG-06）并立即换用新配置，返回保存后的样子。 */
	secretsSet: (config: AiConfigInput) => typedError<AiConfigView, UiError>(__TAURI_INVOKE("secrets_set", { config })),
	/**  逐个模型发一条最小请求，返回可用性和延迟（FR-AIG-04 第 4 条）。没配置大模型时为空列表。 */
	aiTestConnection: () => typedError<ModelProbeView[], UiError>(__TAURI_INVOKE("ai_test_connection")),
	aiUsageToday: () => typedError<UsageRow[], UiError>(__TAURI_INVOKE("ai_usage_today")),
	/**
	 *  一句暖心话上的 👍 有用 / 👎 不合适 / 🔕 今天先别说了。`id` 是 `comfort:new` 带的行号。
	 *  👎 的模板句以后不再出现；🔕 让今天剩余时间不再主动关怀（休息提醒不受影响）；
	 *  连续 3 天都是 👎 / 🔕 时自动降一档，推送 `care:reduced` 和 `settings:changed`。
	 *  这句话已被清理时什么也不做。
	 */
	comfortFeedback: (id: number, verdict: ComfortVerdict) => typedError<null, UiError>(__TAURI_INVOKE("comfort_feedback", { id, verdict })),
	chatListSessions: () => typedError<ChatSessionItem[], UiError>(__TAURI_INVOKE("chat_list_sessions")),
	/**  一个会话的消息，从旧到新。 */
	chatGetMessages: (sessionId: number) => typedError<ChatMessageItem[], UiError>(__TAURI_INVOKE("chat_get_messages", { sessionId })),
	/**
	 *  发一条消息（FR-CHT-02/04/09）。`session_id` 为空或上一条消息已超过 6 小时就开新会话。
	 *  异步命令：回复在 tokio 运行时里的后台任务中生成。
	 */
	chatSend: (sessionId: number | null, text: string) => typedError<ChatSent, UiError>(__TAURI_INVOKE("chat_send", { sessionId, text })),
	/**  “重试”：为会话最后一条用户消息重新生成回复（FR-CHT-04 第 2 条）。 */
	chatRetry: (sessionId: number) => typedError<ChatSent, UiError>(__TAURI_INVOKE("chat_retry", { sessionId })),
	/**  “停止生成”（FR-CHT-04 第 3 条）。已生成的部分照常保存，经 `chat:done`（`stopped = true`）推送。 */
	chatStop: (requestId: number) => typedError<null, UiError>(__TAURI_INVOKE("chat_stop", { requestId })),
	/**  复制一条消息的文本：AI 回复末尾附加“（内容由 AI 生成）”（FR-CHT-04 第 5 条）。剪贴板由前端写。 */
	chatCopy: (messageId: number) => typedError<string, UiError>(__TAURI_INVOKE("chat_copy", { messageId })),
	/**  删除一个会话（FR-CHT-08）。 */
	chatDelete: (sessionId: number) => typedError<null, UiError>(__TAURI_INVOKE("chat_delete", { sessionId })),
	/**  删除全部对话（FR-CHT-08）。 */
	chatDeleteAll: () => typedError<null, UiError>(__TAURI_INVOKE("chat_delete_all")),
	/**  求助卡片上的“我说的不是这个意思”（FR-SAF-06）：本会话回到普通模式、词表阈值提高，求助信息折叠保留。 */
	safetyDismiss: (sessionId: number) => typedError<null, UiError>(__TAURI_INVOKE("safety_dismiss", { sessionId })),
	/**  全部已登记的输入法配置键与类型，设置页据此生成表单。 */
	imeSchema: () => typedError<ImeField[], UiError>(__TAURI_INVOKE("ime_schema")),
	/**  整份合并后的输入法配置。 */
	imeConfigGet: () => typedError<ImeConfig, UiError>(__TAURI_INVOKE("ime_config_get")),
	/**  写入若干项：失败项不让整批失败，`skipped` 里带原因，界面显示在对应控件旁（17 第 3.4 节）。 */
	imeConfigSet: (items: ImeItemInput[]) => typedError<ImeSetResult, UiError>(__TAURI_INVOKE("ime_config_set", { items })),
};

/** Events */
export const events = {
	careReduced: makeEvent<CareReduced>("care:reduced"),
	chatDelta: makeEvent<ChatDelta>("chat:delta"),
	chatDone: makeEvent<ChatDone>("chat:done"),
	chatError: makeEvent<ChatErrorEvent>("chat:error"),
	comfortNew: makeEvent<ComfortNew>("comfort:new"),
	gatewayHealth: makeEvent<GatewayHealthChanged>("gateway:health"),
	imeConfigChanged: makeEvent<ImeConfigChanged>("ime_config:changed"),
	restDue: makeEvent<RestDue>("rest:due"),
	safetyTriggered: makeEvent<SafetyTriggered>("safety:triggered"),
	selfReportChanged: makeEvent<SelfReportChanged>("self_report:changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings:changed"),
	statusChanged: makeEvent<StatusChanged>("status:changed"),
};

/* Types */
/**  设置页保存的内容。某一侧为 `null` 表示清除这一侧；`api_key` 为 `null` 或空字符串表示沿用已保存的密钥。 */
export type AiConfigInput = {
	jev: JevInput | null,
	llm: LlmInput | null,
};

/**  当前 AI 配置从哪里来。 */
export type AiConfigSource = 
/**  设置页保存的 */
"saved" | 
/**  开发版读到了仓库根目录的 secrets.toml */
"dev_file" | 
/**  开发版连本机 mock-ai */
"dev_mock" | 
/**  没有配置，离线模式 */
"none";

/**  设置页“AI 服务”展示的内容：地址、模型和密钥末 4 位，不含密钥本身。 */
export type AiConfigView = {
	source: AiConfigSource,
	jev: JevView | null,
	llm: LlmView | null,
};

export type BudgetKind = 
/**  Jev 调用 */
"jev" | 
/**  大模型调用（不含对话） */
"llm" | 
/**  对话轮数 */
"chat_turn" | 
/**  日程初筛命中的句子 */
"schedule_prefilter" | 
/**  温柔改写 */
"rewrite";

/**
 *  `care:reduced`：连续 3 天的反馈都是 👎 / 🔕，主动关怀频率自动降了一档（FR-CMF-06 第 2 条）。
 *  小组件一句话区显示 `widget.care_reduced`（“我会少打扰你一些”）。`level` 是降档后的 `care.level`。
 */
export type CareReduced = {
	level: string,
};

/**  `chat:delta`：对话回复的一段增量（FR-CHT-04 第 1 条），按到达顺序拼接显示。 */
export type ChatDelta = {
	request_id: number,
	text_delta: string,
};

/**
 *  `chat:done`：回复结束。`text` 是最终写库的全文，校验替换或截断过时与增量拼出来的不同，界面以它为准；
 *  `ai_generated` 为假（固定回应、替换句）时不显示 `AI 生成` 标签。用户停止生成且一个字都没有时 `message_id` 为 `null`。
 */
export type ChatDone = {
	request_id: number,
	session_id: number,
	message_id: number | null,
	text: string,
	ai_generated: boolean,
	stopped: boolean,
};

/**
 *  `chat:error`：没拿到回复（超时、模型不可用、今日额度用完）。用户消息已保存，界面移除半截回复，
 *  显示 `chat.stuck` 或 `chat.daily_cap` 和“重试”（`chat_retry`）。
 */
export type ChatErrorEvent = {
	request_id: number,
	session_id: number,
	reason: ChatFailure,
};

export type ChatFailure = 
/**  超时、模型不可用、网络等：“晴晴有点卡，稍后再试” */
"stuck" | 
/**  今日对话额度用完（FR-AIG-07）：“今天聊了很多啦，明天继续？” */
"daily_cap";

export type ChatMessageItem = {
	id: number,
	/**  `user` / `assistant` / `system_notice` */
	role: string,
	content: string,
	ts: number | null,
	/**  为真时显示 `AI 生成` 标签（FR-CHT-04 第 4 条） */
	ai_generated: boolean,
};

/**  `chat_send` / `chat_retry` 的结果；回复经 `chat:*` 事件推送。 */
export type ChatSent = {
	request_id: number,
	session_id: number,
	user_message_id: number | null,
	/**  开了新会话（没传会话，或上一条消息已超过 6 小时） */
	new_session: boolean,
	/**  本地词表命中：立即显示求助卡片 */
	safety: boolean,
};

/**  左侧抽屉的一行（FR-CHT-02 第 3 条）。时间戳是 Unix 毫秒（前端绑定不导出 i64）。 */
export type ChatSessionItem = {
	id: number,
	title: string,
	created_ts: number | null,
	last_ts: number | null,
	/**  `on` / `dismissed` 时窗口顶部要有求助信息（展开或折叠成一行） */
	safe_mode: SafeMode,
};

/**
 *  `comfort:new`：晴晴说了一句暖心话（FR-CMF-04）。小组件一句话区显示；`ai_generated` 时句尾加 `AI 生成` 标签，
 *  模板句不加。
 */
export type ComfortNew = {
	/**  `comfort_log` 的行号，反馈（FR-CMF-05）时用 */
	id: number,
	text: string,
	source: ComfortSource,
	ai_generated: boolean,
};

/**  暖心话从哪里来：大模型生成的要标 `AI 生成`，模板句不标（FR-CMF-04 第 2 条、FR-CMF-03 第 3 条）。 */
export type ComfortSource = "llm" | "template";

/**  一句暖心话上的反馈（`comfort_log.feedback`）。 */
export type ComfortVerdict = 
/**  👍 有用 */
"useful" | 
/**  👎 不合适 */
"unfit" | 
/**  🔕 今天先别说了 */
"mute";

export type ConsentEntry = {
	item: ConsentItem,
	granted: boolean,
};

export type ConsentItem = 
/**  ① 感知打字节奏，在本机识别状态（使用心晴的前提） */
"sense" | 
/**  ② 数值特征发送给第三方 AI 服务做状态判断 */
"jev_features" | 
/**  ③ 日程与待办识别（发送单句文字） */
"schedule" | 
/**  ④ 状态摘要发给大模型（暖心话、对话、周信） */
"llm_summary" | 
/**  ⑤ 增强模式（发送上屏文字判断情绪） */
"enhanced" | 
/**  ⑥ 温柔改写（按快捷键时发送那段文字） */
"rewrite";

/**  `consent_get` 的返回值：每一项在当前隐私说明版本下是否已同意。 */
export type ConsentState = {
	policy_ver: number,
	items: ConsentEntry[],
};

/**  判断来源（`explain.toml` 的 `[source]`）。 */
export type ExplainSource = "jev" | "rule" | 
/**  自评（FR-STA-10） */
"self";

/**  一次状态解释（`state_explain` 的返回值，10 第 5.1 节）。 */
export type Explanation = {
	state: MoodState,
	/**
	 *  可能性百分比 0–100（快照里的 `prob` 是 0–1 小数，这里用整数百分比，名字上区分）；
	 *  只有本地规则或冷启动时为 `None`，界面不显示百分比。
	 */
	prob_pct: number | null,
	/**  最多 [`MAX_SIGNALS`] 条；为空时界面显示 `note.no_signal`。 */
	signals: Signal[],
	source: ExplainSource,
	/**  冷启动期间追加“还在熟悉你的习惯，判断可能不准”。 */
	cold_start: boolean,
};

/**  反馈对象（`feedback.target`）。 */
export type FeedbackTarget = 
/**  一条状态记录（`mood_state`） */
"mood_state";

/**  两侧是否可用；也是 `gateway:health` 事件的载荷（10 第 5.2 节）。 */
export type GatewayHealth = {
	jev: boolean,
	llm: boolean,
};

/**  `gateway:health`：Jev 与大模型两侧是否可用（`{jev, llm}`），任一侧不可用时小组件显示“离线”角标。 */
export type GatewayHealthChanged = GatewayHealth;

/**  `ime_config_get` 的返回：整份合并后的配置，界面按键名的点分路径取值。 */
export type ImeConfig = {
	values: unknown,
};

/**  输入法配置变了（核心的 `config.changed`，或外壳刚连上事件通道）。界面据此重新取一次配置。 */
export type ImeConfigChange = {
	/**  核心给的原因：`setItems` / `applyPatch` / `reload`；外壳刚连上（核心启动或重启）时是 `connected` */
	reason: string,
	/**  有改动需要重启输入法才生效（FR-SET-01 的重启横幅） */
	needs_restart: boolean,
};

/**
 *  `ime_config:changed`：输入法配置变了（ADR 0017），设置中心的“输入法”分类重新取一次 `ime_config_get`。
 *  来自核心的 `config.changed`（`setItems` / `applyPatch` / `reload`），或外壳刚连上事件通道（`connected`）。
 *  核心自己的语言栏、菜单改的配置不广播，所以设置窗口重新获得焦点时也要取一次。
 */
export type ImeConfigChanged = ImeConfigChange;

/**  `ime_schema` 的一项：已登记的输入法配置键。 */
export type ImeField = {
	/**  点分键名，例如 `ui.candidate.layout` */
	key: string,
	kind: ImeFieldKind,
	/**  只有 `enum` 有：合法取值 */
	options: string[] | null,
};

/**  配置项的类型（`config.schema` 的 `type`），决定界面用什么控件（07 FR-SET-02）。 */
export type ImeFieldKind = "bool" | "int" | "float" | "string" | "enum" | 
/**  字符串数组（schema 里写作 `string[]`） */
"string_list" | "map" | "array" | 
/**  认不出的类型：界面只读显示 JSON */
"other";

/**  `ime_config_set` 的一项：点分键名与新值。 */
export type ImeItemInput = {
	key: string,
	value: unknown,
};

/**  `ime_config_set` 的返回：失败项不让整批失败（`config.setItems` 的语义）。 */
export type ImeSetResult = {
	/**  有改动需要重启输入法才生效（FR-SET-01 的重启横幅） */
	needs_restart: boolean,
	applied: number,
	skipped: ImeSkipped[],
};

/**  被核心跳过的一项（未登记、类型或取值不对……），`reason` 是核心给的原因。 */
export type ImeSkipped = {
	key: string,
	reason: string,
};

export type JevInput = {
	base_url: string,
	api_key: string | null,
	/**  为 `null` 时用 `jev-latest` */
	model: string | null,
};

export type JevView = {
	base_url: string,
	/**  例如 `••••a1b2`；没有密钥时为 `null` */
	key_tail: string | null,
	model: string,
};

export type LlmInput = {
	base_url: string,
	api_key: string | null,
	/**  按优先级排列；为空时用默认模型 */
	models: string[],
};

export type LlmView = {
	base_url: string,
	key_tail: string | null,
	/**  按优先级排列 */
	models: string[],
};

/**  “测试连接”里一个模型的结果（FR-AIG-04 第 4 条）。 */
export type ModelProbeView = {
	model: string,
	ok: boolean,
	latency_ms: number,
	/**  `ok`、HTTP 状态码或 `timeout` / `network` 等错误类别 */
	status: string,
};

/**  显示状态（04 第 3.1 节；`typo` 是瞬时事件，不作为显示状态下发）。 */
export type MoodState = "fluent" | "hesitant" | "low" | "agitated" | "tired" | "unknown";

/**  用户对提醒卡片的操作（FR-RST-06 第 2 条），也是 `reminder_log.action` 的取值。 */
export type RestAction = 
/**  已完成（喝水卡片上叫“喝了”） */
"done" | 
/**  5 分钟后 */
"later" | 
/**  今天不再提醒 */
"today_off";

/**
 *  `rest:due`：该休息了（FR-RST-06）。小组件显示提醒卡片和 `已完成` / `5 分钟后` / `今天不再提醒`，
 *  用户的选择经 `rest_action` 交回后端。`tired` 时护眼卡片换文案“打了很久啦，眼睛也累了吧”（FR-RST-07）。
 */
export type RestDue = {
	kind: RestKind,
	tired: boolean,
};

/**  四类提醒，声明顺序即优先级（高 → 低）。 */
export type RestKind = "night" | "move" | "eye" | "water";

/**  会话的安全状态，存在 `chat_session.safe_mode`（ADR 0018 第 3 条）。 */
export type SafeMode = 
/**  普通模式 */
"off" | 
/**  触发过危机识别：用 P-CHAT-SAFE，求助卡片固定在窗口顶部（FR-SAF-02/03） */
"on" | 
/**  用户点了“我说的不是这个意思”：回到普通模式、词表阈值提高，求助信息仍折叠显示一行（FR-SAF-06） */
"dismissed";

/**
 *  `safety:triggered`：危机识别命中（FR-SAF-01）。对话窗口立即在顶部固定显示求助卡片（FR-SAF-02），
 *  本会话切换为安全模式。
 */
export type SafetyTriggered = {
	session_id: number,
};

/**
 *  `self_report:changed`：用户刚自评（FR-STA-10）。到 `until_ts` 之前小组件显示“你说的：…”；
 *  “说不上来”时 `until_ts` 就是自评时刻，即不覆盖显示。
 */
export type SelfReportChanged = {
	weather: SelfWeather,
	/**  Unix 毫秒（前端绑定不导出 i64，毫秒时间戳在 f64 中是精确的） */
	until_ts: number | null,
};

/**  `self_report_list` 的一行（10 第 5.1 节）。 */
export type SelfReportItem = {
	id: number,
	/**  Unix 毫秒。用 f64 是因为前端绑定不导出 i64，毫秒时间戳在 f64 中是精确的。 */
	ts: number | null,
	weather: SelfWeather,
	/**  只存本地（NFR-PRI-09） */
	note: string | null,
	/**  同一时刻的自动判断 */
	auto_state: MoodState | null,
};

/**  自评选项（`self_report.weather`）。 */
export type SelfWeather = 
/**  ☀️ 挺好 */
"sunny" | 
/**  ⛅ 有点犹豫 */
"cloudy" | 
/**  🌧 有点低落 */
"rain" | 
/**  ⛈ 有点烦 */
"storm" | 
/**  🌙 有点累 */
"night" | 
/**  🤷 说不上来 */
"unsure";

/**  设置项的值。只有这三种形态，对应 [`Kind`]；以 JSON 文本落库（`true` / `0.8` / `"system"`）。 */
export type SettingValue = boolean | number | null | string;

/**  `settings:changed`：只带键名，窗口自行重新读取。 */
export type SettingsChanged = {
	key: string,
};

/**  一条说明。`value` 是文案变量（{p} 百分比、{n} 次数、{m} 分钟）的值。 */
export type Signal = {
	kind: SignalKind,
	value: number | null,
};

/**  说明种类，序列化名就是 `explain.toml` 中 `[signal.*]` 的键。 */
export type SignalKind = 
/**  `kpm_z ≤ -1`，值为 {p} */
"kpm_slow" | 
/**  `kpm_z ≥ 1`，值为 {p} */
"kpm_fast" | 
/**  `iki_med_z ≥ 1` */
"iki_long" | 
/**  `iki_iqr_z ≥ 1.5` */
"iki_messy" | 
/**  `pause_cnt ≥ 2`，值为 {n} */
"pause" | 
/**  `abandon = true` */
"abandon" | 
/**  `delete_committed ≥ 5`，值为 {n} */
"delete_committed" | 
/**  `bs_rate_z ≥ 1` */
"bs_more" | 
/**  `typo_cnt ≥ 2`，值为 {n} */
"typo" | 
/**  `page_flips ≥ 3`，值为 {n} */
"page_flips" | 
/**  `session_min ≥ 45`，值为 {m} */
"session" | 
/**  R5 命中 */
"late";

/**  `status:changed`：载荷同 `get_status`。 */
export type StatusChanged = StatusSnapshot;

/**  `get_status` 的返回值，也是 `status:changed` 事件的载荷。 */
export type StatusSnapshot = {
	state: MoodState,
	weather: Weather,
	/**  当前状态的可能性 0–1；冷启动或只有本地规则时为 `None`，界面不显示百分比。 */
	prob: number | null,
	/**  AI 网关降级为离线模式（FR-AIG-05），小组件显示“离线”角标。 */
	offline: boolean,
	/**  无痕 / 密码框 / 黑名单应用，或用户暂停感知。 */
	paused: boolean,
	/**  与输入法核心的 XQP 连接是否已握手。 */
	connected: boolean,
	/**  基线建立进度 0–100（FR-STA-03 冷启动）。 */
	baseline_progress: number,
};

export type UiError = {
	/**  稳定的错误码，前端可据此分支；只写日志，不展示给用户 */
	code: string,
	/**  `hub_templates/ui_copy.toml` 里的文案键，前端据此显示提示 */
	message_key: string,
};

/**  今日用量的一行（FR-AIG-07、FR-SET-08）。 */
export type UsageRow = {
	kind: BudgetKind,
	used: number,
	cap: number,
};

/**  “准 / 不准”（`feedback.verdict`）。 */
export type Verdict = "fit" | "unfit";

/**  情绪天气（04 第 3.1 节、07 DS-COLOR）。`Wind` 只用于打错字的瞬时动画，不作为持续状态。 */
export type Weather = "sunny" | "wind" | "cloudy" | "rain" | "storm" | "night";

/**
 *  `open_window` 与 `--open` 的目标。标签与 `tauri.conf.json` 的窗口 `label`、
 *  前端 `src/windows/<label>/` 目录一一对应。
 */
export type WindowTarget = "widget" | "chat" | "dashboard" | "settings" | "onboarding";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

