// 本文件由 `cargo run -p xinqing-hub --bin export-bindings` 生成，请勿手改。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getStatus: () => typedError<StatusSnapshot, UiError>(__TAURI_INVOKE("get_status")),
	/**  暂停 / 恢复感知（FR-WGT-06 右键菜单）：进行中的窗口作废，并经 XQP 下发给输入法（FR-SEN-06）。 */
	pauseSet: (on: boolean) => typedError<null, UiError>(__TAURI_INVOKE("pause_set", { on })),
	settingsGet: (key: string) => typedError<SettingValue, UiError>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: SettingValue) => typedError<null, UiError>(__TAURI_INVOKE("settings_set", { key, value })),
	consentGet: () => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_get")),
	/**  记录一项同意或撤回，返回更新后的全部同意状态，界面不用再读一次。 */
	consentSet: (item: ConsentItem, granted: boolean) => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_set", { item, granted })),
	/**  必须是 async：同步命令跑在主线程，在 Windows 上同步命令里建窗口会死锁（wry#583）。 */
	openWindow: (target: WindowTarget) => typedError<null, UiError>(__TAURI_INVOKE("open_window", { target })),
};

/** Events */
export const events = {
	settingsChanged: makeEvent<SettingsChanged>("settings:changed"),
	statusChanged: makeEvent<StatusChanged>("status:changed"),
};

/* Types */
export type ConsentEntry = {
	item: ConsentItem,
	granted: boolean,
};

export type ConsentItem = 
/**  ① 感知打字节奏，在本机识别状态（使用心晴的前提） */
"sense" | 
/**  ② 数值特征发送给第三方 AI 服务做状态判断 */
"jev_features" | 
/**  ③ 日程与待办识别（发送单句文字） */
"schedule" | 
/**  ④ 状态摘要发给大模型（暖心话、对话、周信） */
"llm_summary" | 
/**  ⑤ 增强模式（发送上屏文字判断情绪） */
"enhanced" | 
/**  ⑥ 温柔改写（按快捷键时发送那段文字） */
"rewrite";

/**  `consent_get` 的返回值：每一项在当前隐私说明版本下是否已同意。 */
export type ConsentState = {
	policy_ver: number,
	items: ConsentEntry[],
};

/**  显示状态（04 第 3.1 节；`typo` 是瞬时事件，不作为显示状态下发）。 */
export type MoodState = "fluent" | "hesitant" | "low" | "agitated" | "tired" | "unknown";

/**  设置项的值。只有这三种形态，对应 [`Kind`]；以 JSON 文本落库（`true` / `0.8` / `"system"`）。 */
export type SettingValue = boolean | number | null | string;

/**  `settings:changed`：只带键名，窗口自行重新读取。 */
export type SettingsChanged = {
	key: string,
};

/**  `status:changed`：载荷同 `get_status`。 */
export type StatusChanged = StatusSnapshot;

/**  `get_status` 的返回值，也是 `status:changed` 事件的载荷。 */
export type StatusSnapshot = {
	state: MoodState,
	weather: Weather,
	/**  当前状态的可能性 0–1；冷启动或只有本地规则时为 `None`，界面不显示百分比。 */
	prob: number | null,
	/**  AI 网关降级为离线模式（FR-AIG-05），小组件显示“离线”角标。 */
	offline: boolean,
	/**  无痕 / 密码框 / 黑名单应用，或用户暂停感知。 */
	paused: boolean,
	/**  与输入法核心的 XQP 连接是否已握手。 */
	connected: boolean,
	/**  基线建立进度 0–100（FR-STA-03 冷启动）。 */
	baseline_progress: number,
};

export type UiError = {
	/**  稳定的错误码，前端可据此分支；只写日志，不展示给用户 */
	code: string,
	/**  `hub_templates/ui_copy.toml` 里的文案键，前端据此显示提示 */
	message_key: string,
};

/**  情绪天气（04 第 3.1 节、07 DS-COLOR）。`Wind` 只用于打错字的瞬时动画，不作为持续状态。 */
export type Weather = "sunny" | "wind" | "cloudy" | "rain" | "storm" | "night";

/**
 *  `open_window` 与 `--open` 的目标。标签与 `tauri.conf.json` 的窗口 `label`、
 *  前端 `src/windows/<label>/` 目录一一对应。
 */
export type WindowTarget = "widget" | "chat" | "dashboard" | "settings" | "onboarding";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

