// 本文件由 `cargo run -p xinqing-hub --bin export-bindings` 生成，请勿手改。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getStatus: () => typedError<StatusSnapshot, UiError>(__TAURI_INVOKE("get_status")),
	/**
	 *  导出用户数据（FR-DAT-03），写到前端文件选择器给的 `path`（已存在则覆盖）。
	 *  1 年数据量要几秒，放进 `spawn_blocking`，不占主线程。先提交排队中的数据（ADR 0020 第 3 条最多晚 5 秒），
	 *  再在只读连接上导出，导出期间不挡写入。
	 */
	dataExport: (path: string) => typedError<null, UiError>(__TAURI_INVOKE("data_export", { path })),
	/**
	 *  状态解释（FR-STA-09）。不带 `mood_state_id` 时是当前显示状态的解释（还没切换过时为 `null`）；
	 *  带上时是看板时间线上那个状态点的解释，记录不存在或窗口已清理时为 `null`。
	 */
	stateExplain: (moodStateId: number | null) => typedError<{
	state: MoodState,
	/**
	 *  可能性百分比 0–100（快照里的 `prob` 是 0–1 小数，这里用整数百分比，名字上区分）；
	 *  只有本地规则或冷启动时为 `None`，界面不显示百分比。
	 */
	prob_pct: number | null,
	/**  最多 [`MAX_SIGNALS`] 条；为空时界面显示 `note.no_signal`。 */
	signals: Signal[],
	source: ExplainSource,
	/**  冷启动期间追加“还在熟悉你的习惯，判断可能不准”。 */
	cold_start: boolean,
} | null, UiError>(__TAURI_INVOKE("state_explain", { moodStateId })),
	/**
	 *  状态“准 / 不准”（FR-STA-07）。不带 `target_id` 时评价的是当前显示状态。
	 *  写入 `feedback` 表后，“不准”交给感知任务上调个人阈值；交不过去时（任务没运行或队列满）
	 *  也不报错，下次启动会从库里重放。还没有任何状态记录时什么也不做。
	 */
	submitFeedback: (target: FeedbackTarget, targetId: number | null, verdict: Verdict) => typedError<null, UiError>(__TAURI_INVOKE("submit_feedback", { target, targetId, verdict })),
	/**
	 *  主动报告心情（FR-STA-10）。写入 `self_report` 表后交给感知任务：之后 60 分钟显示用户说的状态
	 *  （“说不上来”不覆盖），并推送 `self_report:changed`。备注只存本地，用完即清零（NFR-PRI-09）。
	 *  研究模式的邀请（`research:invite`）弹出后 30 分钟内的自评记为 `source = esm`（FR-DMO-04）。
	 */
	selfReportSet: (weather: SelfWeather, note: string | null) => typedError<null, UiError>(__TAURI_INVOKE("self_report_set", { weather, note })),
	/**  某天（本地日期 `YYYY-MM-DD`）的自评，按时间先后；看板时间线用实心标记显示。 */
	selfReportList: (date: string) => typedError<SelfReportItem[], UiError>(__TAURI_INVOKE("self_report_list", { date })),
	/**
	 *  重置基线（设置页“感知”分类，FR-SET-04、FR-STA-03 第 4 条）：清空个人统计值，
	 *  之后只用重置以后的窗口，重新进入冷启动（“正在熟悉你的打字习惯”从 0% 开始）。
	 */
	baselineReset: () => typedError<null, UiError>(__TAURI_INVOKE("baseline_reset")),
	/**
	 *  作息洞察（FR-REV-03，看板周报）：截至最近一个已经结束的晚上共 `days` 晚（1–90）的停止打字时间。
	 *  界面一律称“停止打字时间”，并注明只统计这台电脑上的打字、不等于入睡时间（DS-COPY-09）。
	 */
	getRoutine: (days: number) => typedError<Routine, UiError>(__TAURI_INVOKE("get_routine", { days })),
	/**  是否为演示模式（FR-DMO-03）：是的话界面在标题栏显示“演示模式”。以 `--demo` 启动时为是（ADR 0023）。 */
	demoStatus: () => typedError<DemoStatus, UiError>(__TAURI_INVOKE("demo_status")),
	/**  研究模式的自评邀请点了“跳过”（FR-DMO-04）：之后的自评按用户主动报告记。 */
	researchDismiss: () => typedError<null, UiError>(__TAURI_INVOKE("research_dismiss")),
	/**
	 *  删除研究期间邀请得到的自评（`source = esm`，FR-DMO-04“研究结束后删除”），返回删了几条。
	 *  用户主动的自评不动。界面应先请用户确认。
	 */
	researchClear: () => typedError<number, UiError>(__TAURI_INVOKE("research_clear")),
	/**  暂停 / 恢复感知（FR-WGT-06 右键菜单）：进行中的窗口作废，并经 XQP 下发给输入法（FR-SEN-06）。 */
	pauseSet: (on: boolean) => typedError<null, UiError>(__TAURI_INVOKE("pause_set", { on })),
	/**  全部设置键的类型、取值范围与默认值（ADR 0019 第 9 条），设置页按它出控件，与 `ime_schema` 对称。 */
	settingsSchema: () => __TAURI_INVOKE<SettingField[]>("settings_schema"),
	settingsGet: (key: string) => typedError<SettingValue, UiError>(__TAURI_INVOKE("settings_get", { key })),
	settingsSet: (key: string, value: SettingValue) => typedError<null, UiError>(__TAURI_INVOKE("settings_set", { key, value })),
	consentGet: () => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_get")),
	/**  记录一项同意或撤回，返回更新后的全部同意状态，界面不用再读一次。 */
	consentSet: (item: ConsentItem, granted: boolean) => typedError<ConsentState, UiError>(__TAURI_INVOKE("consent_set", { item, granted })),
	/**  必须是 async：同步命令跑在主线程，在 Windows 上同步命令里建窗口会死锁（wry#583）。 */
	openWindow: (target: WindowTarget) => typedError<null, UiError>(__TAURI_INVOKE("open_window", { target })),
	/**
	 *  全局快捷键的注册结果（FR-ENT-04，设置页“常规”）：`conflict` 为真的是设了但没注册上（被别的软件占用，
	 *  或与另一项重复），界面提示换一个，不弹窗打扰（07 FR-ENT-04）。
	 */
	hotkeyStatus: () => __TAURI_INVOKE<HotkeyStatus[]>("hotkey_status"),
	/**
	 *  用户点了休息提醒卡片上的按钮（FR-RST-06 第 2 条）：完成或关闭后该类计时清零，“5 分钟后”顺延；
	 *  每次操作记一条 `reminder_log`（FR-RST-08）。服务没在运行时忽略。
	 */
	restAction: (kind: RestKind, action: RestAction) => typedError<null, UiError>(__TAURI_INVOKE("rest_action", { kind, action })),
	aiConfigGet: () => typedError<AiConfigView, UiError>(__TAURI_INVOKE("ai_config_get")),
	/**  保存 AI 服务地址与密钥（FR-AIG-06）并立即换用新配置，返回保存后的样子。 */
	secretsSet: (config: AiConfigInput) => typedError<AiConfigView, UiError>(__TAURI_INVOKE("secrets_set", { config })),
	/**  逐个模型发一条最小请求，返回可用性和延迟（FR-AIG-04 第 4 条）。没配置大模型时为空列表。 */
	aiTestConnection: () => typedError<ModelProbeView[], UiError>(__TAURI_INVOKE("ai_test_connection")),
	aiUsageToday: () => typedError<UsageRow[], UiError>(__TAURI_INVOKE("ai_usage_today")),
	/**
	 *  读取当前网关的内存指标（FR-AIG-08），不发请求、不扣预算、不落盘。
	 *  接口按名称排序，模型按配置优先级排列；Hub 重启或更换网关配置后统计清空。
	 */
	aiGatewayMetrics: () => typedError<GatewayMetricsView, UiError>(__TAURI_INVOKE("ai_gateway_metrics")),
	/**
	 *  返回设置页需要的最近出网记录（FR-SET-09、09 D-20）。数据库本身只保留最近 200 条，
	 *  界面再取最近 20 条；记录不含用户输入、提示词或模型回复。
	 */
	aiNetLogRecent: () => typedError<NetLogView[], UiError>(__TAURI_INVOKE("ai_net_log_recent")),
	/**
	 *  一句暖心话上的 👍 有用 / 👎 不合适 / 🔕 今天先别说了。`id` 是 `comfort:new` 带的行号。
	 *  👎 的模板句以后不再出现；🔕 让今天剩余时间不再主动关怀（休息提醒不受影响）；
	 *  连续 3 天都是 👎 / 🔕 时自动降一档，推送 `care:reduced` 和 `settings:changed`。
	 *  这句话已被清理时什么也不做。
	 */
	comfortFeedback: (id: number, verdict: ComfortVerdict) => typedError<null, UiError>(__TAURI_INVOKE("comfort_feedback", { id, verdict })),
	/**  某天（本地日期 `YYYY-MM-DD`）的暖心话，从早到晚（FR-DSH-02“今日一句”、FR-WGT-04“今日一句”）。 */
	comfortList: (date: string) => typedError<ComfortItem[], UiError>(__TAURI_INVOKE("comfort_list", { date })),
	/**  某天的概要（FR-DSH-02 概要卡片与状态时间线、FR-WGT-05 今日输入时长）。没有记录的天全是 0。 */
	dayStats: (date: string) => typedError<DayStats, UiError>(__TAURI_INVOKE("day_stats", { date })),
	/**  情绪日历的一个月（FR-DSH-03）：`month` 是 `YYYY-MM`，返回这个月每天的主导天气与有没有日记。 */
	monthMoods: (month: string) => typedError<DayMood[], UiError>(__TAURI_INVOKE("month_moods", { month })),
	/**
	 *  周报（FR-DSH-04）：`week_start` 是那周里的任意一天，按所在周的周一算。作息洞察另用 `get_routine`。
	 *  一句话总结来自本地模板 `weekly_line.toml`，不调用 AI；模板读不出来时用一句兜底。
	 */
	weekStats: (weekStart: string) => typedError<WeekReport, UiError>(__TAURI_INVOKE("week_stats", { weekStart })),
	/**  全部周信，新的在前（保留 1 年）。 */
	lettersList: () => typedError<LetterItem[], UiError>(__TAURI_INVOKE("letters_list")),
	/**  标记已读。这封已被删除或清理时什么也不做。 */
	letterRead: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("letter_read", { id })),
	/**  删除一封（删掉的不会重写）。这封已被删除或清理时什么也不做。 */
	letterDelete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("letter_delete", { id })),
	chatListSessions: () => typedError<ChatSessionItem[], UiError>(__TAURI_INVOKE("chat_list_sessions")),
	/**  一个会话的消息，从旧到新。 */
	chatGetMessages: (sessionId: number) => typedError<ChatMessageItem[], UiError>(__TAURI_INVOKE("chat_get_messages", { sessionId })),
	/**
	 *  切换会话的对话方式（FR-CHT-06“我只是想吐槽”“帮我理一理”，回到平常用 `normal`），下一次回复起生效。
	 *  还没有会话时不调这个，在 `chat_send` 里带上 `mode`。“写成情绪日记”“陪我呼吸”是窗口的本地动作。
	 */
	chatSetMode: (sessionId: number, mode: ChatMode) => typedError<null, UiError>(__TAURI_INVOKE("chat_set_mode", { sessionId, mode })),
	chatSearch: (query: string) => typedError<ChatSearchItem[], UiError>(__TAURI_INVOKE("chat_search", { query })),
	memoryList: () => typedError<MemoryItem[], UiError>(__TAURI_INVOKE("memory_list")),
	/**
	 *  记住一件事（FR-CHT-07）。已有 50 条时返回 `chat.memory_full`，前端提示先删掉几条。
	 *  记忆是用户确认类数据，同步写（ADR 0020 第 4 条）。
	 */
	memoryAdd: (content: string) => typedError<number, UiError>(__TAURI_INVOKE("memory_add", { content })),
	memoryUpdate: (id: number, content: string) => typedError<null, UiError>(__TAURI_INVOKE("memory_update", { id, content })),
	memoryDelete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("memory_delete", { id })),
	/**
	 *  发一条消息（FR-CHT-02/04/09）。`session_id` 为空或上一条消息已超过 6 小时就开新会话。
	 *  `mode` 不为空时先把会话切到这种对话方式（快捷指令后发的第一句，ADR 0022）。
	 *  异步命令：回复在 tokio 运行时里的后台任务中生成。
	 */
	chatSend: (sessionId: number | null, text: string, mode: 
/**  平常的对话 */
"normal" | 
/**  💬 我只是想吐槽：本会话只倾听，只共情和复述，不给建议 */
"vent" | 
/**  🧭 帮我理一理：引导说清“发生了什么 / 我的感受 / 我能做的一小步” */
"organize" | null) => typedError<ChatSent, UiError>(__TAURI_INVOKE("chat_send", { sessionId, text, mode })),
	/**  “重试”：为会话最后一条用户消息重新生成回复（FR-CHT-04 第 2 条）。 */
	chatRetry: (sessionId: number) => typedError<ChatSent, UiError>(__TAURI_INVOKE("chat_retry", { sessionId })),
	/**  “停止生成”（FR-CHT-04 第 3 条）。已生成的部分照常保存，经 `chat:done`（`stopped = true`）推送。 */
	chatStop: (requestId: number) => typedError<null, UiError>(__TAURI_INVOKE("chat_stop", { requestId })),
	/**  复制一条消息的文本：AI 回复末尾附加“（内容由 AI 生成）”（FR-CHT-04 第 5 条）。剪贴板由前端写。 */
	chatCopy: (messageId: number) => typedError<string, UiError>(__TAURI_INVOKE("chat_copy", { messageId })),
	/**  删除一个会话（FR-CHT-08）。 */
	chatDelete: (sessionId: number) => typedError<null, UiError>(__TAURI_INVOKE("chat_delete", { sessionId })),
	/**  删除全部对话（FR-CHT-08）。 */
	chatDeleteAll: () => typedError<null, UiError>(__TAURI_INVOKE("chat_delete_all")),
	/**  求助卡片上的“我说的不是这个意思”（FR-SAF-06）：本会话回到普通模式、词表阈值提高，求助信息折叠保留。 */
	safetyDismiss: (sessionId: number) => typedError<null, UiError>(__TAURI_INVOKE("safety_dismiss", { sessionId })),
	/**
	 *  小组件一句话区的求助入口（收到 `safety:invite` 后显示，ADR 0028 第 4 条）：开一段安全模式的对话，
	 *  打开对话窗口并显示求助卡片。返回这段对话的 `session_id`。
	 */
	safetyOpen: () => typedError<number, UiError>(__TAURI_INVOKE("safety_open")),
	/**
	 *  生成今天的日记草稿（FR-DIA-01）。从对话窗口“写成情绪日记”进来时带上那段对话的 `session_id`，
	 *  看板“写今天的日记”不带。最长约 20 秒；大模型不可用时立即给空白模板。
	 */
	diaryGenerate: (sessionId: number | null) => typedError<DiaryDraft, UiError>(__TAURI_INVOKE("diary_generate", { sessionId })),
	/**
	 *  保存日记（FR-DIA-02/03）：`id` 为空时新写一篇（记在今天），否则修改那一篇。从草稿来的带上 `draft_id`，
	 *  手写的不带。来源由后端判断。返回时已落盘。
	 */
	diarySave: (id: number | null, draftId: number | null, content: string) => typedError<DiarySaved, UiError>(__TAURI_INVOKE("diary_save", { id, draftId, content })),
	/**  全部日记，新的在前（FR-DIA-03）。 */
	diaryList: () => typedError<DiaryItem[], UiError>(__TAURI_INVOKE("diary_list")),
	/**  删除一篇（FR-DIA-03）。这篇已被删除时什么也不做。 */
	diaryDelete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("diary_delete", { id })),
	/**  某个状态的日程（FR-SCH-09）：`pending` / `added` / `ignored`（只有数量有意义）。“已过期”是已添加里日期已过的，界面自己分。 */
	scheduleList: (status: string) => typedError<ScheduleItem[], UiError>(__TAURI_INVOKE("schedule_list", { status })),
	/**  卡片或待确认列表里的“添加”（FR-SCH-05）：待确认 → 已添加，按 FR-SCH-07 开始提醒。 */
	scheduleConfirm: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("schedule_confirm", { id })),
	/**  “忽略”（FR-SCH-05）：只留去重哈希，标题等立即删除。 */
	scheduleIgnore: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("schedule_ignore", { id })),
	/**  手动新建（FR-SCH-09）：直接是已添加，不带 `AI 识别`。返回与之时间重叠的日程（FR-SCH-11）。 */
	scheduleCreate: (input: ScheduleInput) => typedError<ScheduleSaved, UiError>(__TAURI_INVOKE("schedule_create", { input })),
	/**  修改（卡片上的“修改”、日程页编辑，FR-SCH-05、FR-SCH-09）。来源不变，标记清空（用户改过就以用户为准）。 */
	scheduleUpdate: (id: number, input: ScheduleInput) => typedError<ScheduleSaved, UiError>(__TAURI_INVOKE("schedule_update", { id, input })),
	/**  删除（FR-SCH-09）。 */
	scheduleDelete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("schedule_delete", { id })),
	/**
	 *  加入我的日历（FR-SCH-08）：把这些日程写成 RFC 5545 `.ics` 放进临时目录，Windows 上用系统默认程序打开。
	 *  返回文件路径。没有日期的日程跳过。
	 */
	scheduleExportIcs: (ids: number[]) => typedError<string, UiError>(__TAURI_INVOKE("schedule_export_ics", { ids })),
	/**  提醒卡片上的操作（FR-SCH-07）：`ok` 知道了、`snooze_5` / `snooze_10` 5 / 10 分钟后再提醒。`id` 是 `reminder:due` 带的。 */
	reminderAction: (id: number, action: string) => typedError<null, UiError>(__TAURI_INVOKE("reminder_action", { id, action })),
	/**  某个状态的待办（FR-SCH-13）：`pending` / `open` / `done` / `archived`。 */
	todoList: (status: string) => typedError<TodoItem[], UiError>(__TAURI_INVOKE("todo_list", { status })),
	/**  卡片上的“加入待办”（FR-SCH-13）：待确认 → 未完成。 */
	todoConfirm: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("todo_confirm", { id })),
	/**  “忽略”：只留去重哈希。 */
	todoIgnore: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("todo_ignore", { id })),
	/**  手动新建（FR-SCH-13）：直接是未完成，不带 `AI 识别`。返回行号。 */
	todoCreate: (input: TodoInput) => typedError<number, UiError>(__TAURI_INVOKE("todo_create", { input })),
	/**  修改待确认或未完成的待办。 */
	todoUpdate: (id: number, input: TodoInput) => typedError<null, UiError>(__TAURI_INVOKE("todo_update", { id, input })),
	/**  勾选完成（FR-SCH-13）：7 天后归档、30 天后删除（数据保留期，`retention`）。 */
	todoComplete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("todo_complete", { id })),
	/**  删除。 */
	todoDelete: (id: number) => typedError<null, UiError>(__TAURI_INVOKE("todo_delete", { id })),
	/**  全部已登记的输入法配置键与类型，设置页据此生成表单。 */
	imeSchema: () => typedError<ImeField[], UiError>(__TAURI_INVOKE("ime_schema")),
	/**  整份合并后的输入法配置。 */
	imeConfigGet: () => typedError<ImeConfig, UiError>(__TAURI_INVOKE("ime_config_get")),
	/**  写入若干项：失败项不让整批失败，`skipped` 里带原因，界面显示在对应控件旁（17 第 3.4 节）。 */
	imeConfigSet: (items: ImeItemInput[]) => typedError<ImeSetResult, UiError>(__TAURI_INVOKE("ime_config_set", { items })),
};

/** Events */
export const events = {
	careReduced: makeEvent<CareReduced>("care:reduced"),
	chatDelta: makeEvent<ChatDelta>("chat:delta"),
	chatDone: makeEvent<ChatDone>("chat:done"),
	chatError: makeEvent<ChatErrorEvent>("chat:error"),
	comfortNew: makeEvent<ComfortNew>("comfort:new"),
	gatewayHealth: makeEvent<GatewayHealthChanged>("gateway:health"),
	imeConfigChanged: makeEvent<ImeConfigChanged>("ime_config:changed"),
	letterNew: makeEvent<LetterNew>("letter:new"),
	moodTypo: makeEvent<MoodTypo>("mood:typo"),
	reminderDue: makeEvent<ReminderDue>("reminder:due"),
	reminderMissed: makeEvent<ReminderMissed>("reminder:missed"),
	researchInvite: makeEvent<ResearchInvite>("research:invite"),
	restDue: makeEvent<RestDue>("rest:due"),
	reviewEvening: makeEvent<ReviewEvening>("review:evening"),
	safetyInvite: makeEvent<SafetyInvite>("safety:invite"),
	safetyTriggered: makeEvent<SafetyTriggered>("safety:triggered"),
	scheduleDetected: makeEvent<ScheduleDetected>("schedule:detected"),
	scheduleReady: makeEvent<ScheduleReady>("schedule:ready"),
	selfReportChanged: makeEvent<SelfReportChanged>("self_report:changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings:changed"),
	statusChanged: makeEvent<StatusChanged>("status:changed"),
	todoDetected: makeEvent<TodoDetected>("todo:detected"),
	todoReady: makeEvent<TodoReady>("todo:ready"),
	typingPulse: makeEvent<TypingPulse>("typing:pulse"),
};

/* Types */
/**  设置页保存的内容。某一侧为 `null` 表示清除这一侧；`api_key` 为 `null` 或空字符串表示沿用已保存的密钥。 */
export type AiConfigInput = {
	jev: JevInput | null,
	llm: LlmInput | null,
};

/**  当前 AI 配置从哪里来。 */
export type AiConfigSource = 
/**  设置页保存的 */
"saved" | 
/**  开发版读到了仓库根目录的 secrets.toml */
"dev_file" | 
/**  开发版连本机 mock-ai */
"dev_mock" | 
/**  没有配置，离线模式 */
"none";

/**  设置页“AI 服务”展示的内容：地址、模型和密钥末 4 位，不含密钥本身。 */
export type AiConfigView = {
	source: AiConfigSource,
	jev: JevView | null,
	llm: LlmView | null,
};

export type ApiMetricsView = {
	api: string,
	calls: number,
	ok: number,
	/**  成功次数 / 调用次数（0～1）；没有调用时为空。 */
	success_rate: number | null,
	p50_ms: number | null,
	p95_ms: number | null,
	breaker_open: boolean,
};

export type BudgetKind = 
/**  Jev 调用 */
"jev" | 
/**  大模型调用（不含对话） */
"llm" | 
/**  对话轮数 */
"chat_turn" | 
/**  日程初筛命中的句子 */
"schedule_prefilter" | 
/**  温柔改写 */
"rewrite";

/**
 *  `care:reduced`：连续 3 天的反馈都是 👎 / 🔕，主动关怀频率自动降了一档（FR-CMF-06 第 2 条）。
 *  小组件一句话区显示 `widget.care_reduced`（“我会少打扰你一些”）。`level` 是降档后的 `care.level`。
 */
export type CareReduced = {
	level: string,
};

/**  `chat:delta`：对话回复的一段增量（FR-CHT-04 第 1 条），按到达顺序拼接显示。 */
export type ChatDelta = {
	request_id: number,
	text_delta: string,
};

/**
 *  `chat:done`：回复结束。`text` 是最终写库的全文，校验替换或截断过时与增量拼出来的不同，界面以它为准；
 *  `ai_generated` 为假（固定回应、替换句）时不显示 `AI 生成` 标签。用户停止生成且一个字都没有时 `message_id` 为 `null`。
 */
export type ChatDone = {
	request_id: number,
	session_id: number,
	message_id: number | null,
	text: string,
	ai_generated: boolean,
	stopped: boolean,
};

/**
 *  `chat:error`：没拿到回复（超时、模型不可用、今日额度用完）。用户消息已保存，界面移除半截回复，
 *  显示 `chat.stuck` 或 `chat.daily_cap` 和“重试”（`chat_retry`）。
 */
export type ChatErrorEvent = {
	request_id: number,
	session_id: number,
	reason: ChatFailure,
};

export type ChatFailure = 
/**  超时、模型不可用、网络等：“晴晴有点卡，稍后再试” */
"stuck" | 
/**  今日对话额度用完（FR-AIG-07）：“今天聊了很多啦，明天继续？” */
"daily_cap";

export type ChatMessageItem = {
	id: number,
	/**  `user` / `assistant` / `system_notice` */
	role: string,
	content: string,
	ts: number,
	/**  为真时显示 `AI 生成` 标签（FR-CHT-04 第 4 条） */
	ai_generated: boolean,
};

/**
 *  会话的对话方式（FR-CHT-06 快捷指令里要调用 AI 的两个），存在 `chat_session.mode`（ADR 0022）。
 *  “写成情绪日记”“陪我呼吸”是窗口里的本地动作，不经过这里。
 */
export type ChatMode = 
/**  平常的对话 */
"normal" | 
/**  💬 我只是想吐槽：本会话只倾听，只共情和复述，不给建议 */
"vent" | 
/**  🧭 帮我理一理：引导说清“发生了什么 / 我的感受 / 我能做的一小步” */
"organize";

export type ChatSearchItem = {
	id: number,
	session_id: number,
	title: string,
	role: string,
	content: string,
	ts: number,
};

/**  `chat_send` / `chat_retry` 的结果；回复经 `chat:*` 事件推送。 */
export type ChatSent = {
	request_id: number,
	session_id: number,
	user_message_id: number | null,
	/**  开了新会话（没传会话，或上一条消息已超过 6 小时） */
	new_session: boolean,
	/**  本地词表命中：立即显示求助卡片 */
	safety: boolean,
	/**  用户明确要求记住的内容：先问“要让晴晴记住这件事吗？”，确认后调 `memory_add`（FR-CHT-07 第 1 条） */
	memory_candidate: string | null,
};

/**  左侧抽屉的一行（FR-CHT-02 第 3 条）。时间戳是 Unix 毫秒（前端绑定不导出 i64）。 */
export type ChatSessionItem = {
	id: number,
	title: string,
	created_ts: number,
	last_ts: number,
	/**  `on` / `dismissed` 时窗口顶部要有求助信息（展开或折叠成一行） */
	safe_mode: SafeMode,
	/**  快捷指令切换的对话方式（FR-CHT-06，ADR 0022），窗口据此显示“只倾听中”等提示 */
	mode: ChatMode,
};

/**  一句暖心话（看板“今日一句”、小组件重开时的“今日一句”）。时间戳是 Unix 毫秒。 */
export type ComfortItem = {
	id: number,
	ts: number,
	text: string,
	/**  为真时句尾显示 `AI 生成`（FR-CMF-04 第 2 条） */
	ai_generated: boolean,
	trigger: ComfortTrigger,
	/**  用户点过的反馈（FR-CMF-05）；没点过为空 */
	feedback: ComfortVerdict | null,
};

/**
 *  `comfort:new`：晴晴说了一句暖心话（FR-CMF-04）。小组件一句话区显示；`ai_generated` 时句尾加 `AI 生成` 标签，
 *  模板句不加。`trigger` 为 `self_report` 时是负面自评后的回应：卡片层另显示“和晴晴聊聊”（FR-STA-10 第 2 条，ADR 0036）。
 */
export type ComfortNew = {
	/**  `comfort_log` 的行号，反馈（FR-CMF-05）时用 */
	id: number,
	text: string,
	source: ComfortSource,
	ai_generated: boolean,
	trigger: ComfortTrigger,
};

/**  暖心话从哪里来：大模型生成的要标 `AI 生成`，模板句不标（FR-CMF-04 第 2 条、FR-CMF-03 第 3 条）。 */
export type ComfortSource = "llm" | "template";

/**  为什么说这句话。也随 `comfort:new` 交给界面：自评后的回应在小组件上带“和晴晴聊聊”（FR-STA-10 第 2 条，ADR 0036）。 */
export type ComfortTrigger = 
/**  主动关怀（FR-CMF-01） */
"auto" | 
/**  负面自评后的回应（FR-STA-10 第 2 条） */
"self_report";

/**  一句暖心话上的反馈（`comfort_log.feedback`）。 */
export type ComfortVerdict = 
/**  👍 有用 */
"useful" | 
/**  👎 不合适 */
"unfit" | 
/**  🔕 今天先别说了 */
"mute";

/**  与之时间重叠的已添加日程（FR-SCH-11）：卡片上“⚠ 与「班会」时间重叠（15:00–16:00）”。 */
export type ConflictItem = {
	id: number,
	title: string,
	/**  全天日程为 `null` */
	start: string | null,
	end: string | null,
};

export type ConsentEntry = {
	item: ConsentItem,
	granted: boolean,
};

export type ConsentItem = 
/**  ① 感知打字节奏，在本机识别状态（使用心晴的前提） */
"sense" | 
/**  ② 数值特征发送给第三方 AI 服务做状态判断 */
"jev_features" | 
/**  ③ 日程与待办识别（发送单句文字） */
"schedule" | 
/**  ④ 状态摘要发给大模型（暖心话、对话、周信） */
"llm_summary" | 
/**  ⑤ 增强模式（发送上屏文字判断情绪） */
"enhanced" | 
/**  ⑥ 温柔改写（按快捷键时发送那段文字） */
"rewrite";

/**  `consent_get` 的返回值：每一项在当前隐私说明版本下是否已同意。 */
export type ConsentState = {
	policy_ver: number,
	items: ConsentEntry[],
};

/**  情绪日历的一天（FR-DSH-03）。 */
export type DayMood = {
	date: string,
	dominant: MoodState | null,
	/**  当天有日记：日历上画小本子图标（FR-DIA-03） */
	has_diary: boolean,
};

/**  某天的概要（看板“今日”的四张概要卡片与时间线、小组件底栏的今日输入时长）。 */
export type DayStats = {
	/**  本地日期 `YYYY-MM-DD` */
	date: string,
	/**  输入时长（分钟，FR-RST-01 的活跃分钟） */
	typing_min: number,
	/**  休息提醒：出现 / 完成次数；完成率 = 完成 / 出现（FR-RST-08） */
	rests_due: number,
	rests_done: number,
	water: number,
	/**  暖心话次数（含自评后的回应） */
	comforts: number,
	/**  主导天气（[`dominant`]）；有效窗口不足时为空 */
	dominant: MoodState | null,
	timeline: Segment[],
};

/**  `demo_status`：界面据此在标题栏显示“演示模式”（FR-DMO-03）。 */
export type DemoStatus = {
	enabled: boolean,
	/**  时间加速倍数；不是演示模式时为 1 */
	speed: number,
};

/**  `diary_generate` 的结果：草稿或空白模板，放进编辑框让用户改。 */
export type DiaryDraft = {
	/**  保存时原样带回 `diary_save`；空白模板时为 `null` */
	draft_id: number | null,
	text: string,
	/**  为假时是空白模板（大模型不可用、草稿没通过校验、或没有可写的内容） */
	ai_generated: boolean,
};

/**  一篇日记。时间戳是 Unix 毫秒（前端绑定不导出 i64）。 */
export type DiaryItem = {
	id: number,
	/**  本地日期 `YYYY-MM-DD` */
	date: string,
	content: string,
	/**  `ai_draft` 标“AI 生成”，`ai_edited` 标“AI 辅助生成”，`manual` 不标（FR-DIA-02） */
	source: string,
	created_ts: number,
	updated_ts: number,
};

/**  `diary_save` 的结果。 */
export type DiarySaved = {
	id: number,
	/**  `ai_draft` / `ai_edited` / `manual`（FR-DIA-02） */
	source: string,
	/**  本地词表命中：对话窗口已打开并显示求助卡片（FR-SAF-02 第 2 条） */
	safety: boolean,
};

/**  晚间小结卡片的内容（`review:evening` 事件）。只有统计值和一句本地模板。 */
export type EveningSummary = {
	/**  哪一天的小结（本地 `YYYY-MM-DD`） */
	date: string,
	/**  打字时长（分钟） */
	typing_min: number,
	/**  喝水次数（点了喝水提醒的“已完成”） */
	water: number,
	/**  休息提醒：完成 / 出现次数 */
	rests_done: number,
	rests_due: number,
	/**  完成的日程（当天已到点、已加入的日程）与待办数 */
	schedules_done: number,
	todos_done: number,
	/**  天气色带，从早到晚 */
	band: MoodState[],
	/**  结束语（本地模板，不加 AI 标识） */
	line: string,
};

/**  判断来源（`explain.toml` 的 `[source]`）。 */
export type ExplainSource = "jev" | "rule" | 
/**  自评（FR-STA-10） */
"self";

/**  一次状态解释（`state_explain` 的返回值，10 第 5.1 节）。 */
export type Explanation = {
	state: MoodState,
	/**
	 *  可能性百分比 0–100（快照里的 `prob` 是 0–1 小数，这里用整数百分比，名字上区分）；
	 *  只有本地规则或冷启动时为 `None`，界面不显示百分比。
	 */
	prob_pct: number | null,
	/**  最多 [`MAX_SIGNALS`] 条；为空时界面显示 `note.no_signal`。 */
	signals: Signal[],
	source: ExplainSource,
	/**  冷启动期间追加“还在熟悉你的习惯，判断可能不准”。 */
	cold_start: boolean,
};

/**  反馈对象（`feedback.target`）。 */
export type FeedbackTarget = 
/**  一条状态记录（`mood_state`） */
"mood_state";

/**  两侧是否可用；也是 `gateway:health` 事件的载荷（10 第 5.2 节）。 */
export type GatewayHealth = {
	jev: boolean,
	llm: boolean,
};

/**  `gateway:health`：Jev 与大模型两侧是否可用（`{jev, llm}`），任一侧不可用时小组件显示“离线”角标。 */
export type GatewayHealthChanged = GatewayHealth;

/**  演示者视图与设置页读取的内存指标；不含地址、密钥、请求或响应正文。 */
export type GatewayMetricsView = {
	apis: ApiMetricsView[],
	models: ModelStatusView[],
};

/**  快捷键做什么。 */
export type HotkeyAction = 
/**  打开对话（FR-CHT-01） */
"chat" | 
/**  显示 / 隐藏小组件（FR-WGT-01） */
"widget" | 
/**  打开看板 */
"dashboard";

/**  一项快捷键现在的样子（设置页“常规”分类）。 */
export type HotkeyStatus = {
	action: HotkeyAction,
	/**  设置里的组合键（规范写法，如 `ctrl+alt+q`）；空串表示没设 */
	keys: string,
	/**  设了但没注册上：被别的软件占用，或与另一项重复。界面提示 `error.hotkey_conflict` */
	conflict: boolean,
};

/**  `ime_config_get` 的返回：整份合并后的配置，界面按键名的点分路径取值。 */
export type ImeConfig = {
	values: unknown,
};

/**  输入法配置变了（核心的 `config.changed`，或外壳刚连上事件通道）。界面据此重新取一次配置。 */
export type ImeConfigChange = {
	/**  核心给的原因：`setItems` / `applyPatch` / `reload`；外壳刚连上（核心启动或重启）时是 `connected` */
	reason: string,
	/**  有改动需要重启输入法才生效（FR-SET-01 的重启横幅） */
	needs_restart: boolean,
};

/**
 *  `ime_config:changed`：输入法配置变了（ADR 0017），设置中心的“输入法”分类重新取一次 `ime_config_get`。
 *  来自核心的 `config.changed`（`setItems` / `applyPatch` / `reload`），或外壳刚连上事件通道（`connected`）。
 *  核心自己的语言栏、菜单改的配置不广播，所以设置窗口重新获得焦点时也要取一次。
 */
export type ImeConfigChanged = ImeConfigChange;

/**  `ime_schema` 的一项：已登记的输入法配置键。 */
export type ImeField = {
	/**  点分键名，例如 `ui.candidate.layout` */
	key: string,
	kind: ImeFieldKind,
	/**  只有 `enum` 有：合法取值 */
	options: string[] | null,
};

/**  配置项的类型（`config.schema` 的 `type`），决定界面用什么控件（07 FR-SET-02）。 */
export type ImeFieldKind = "bool" | "int" | "float" | "string" | "enum" | 
/**  字符串数组（schema 里写作 `string[]`） */
"string_list" | "map" | "array" | 
/**  认不出的类型：界面只读显示 JSON */
"other";

/**  `ime_config_set` 的一项：点分键名与新值。 */
export type ImeItemInput = {
	key: string,
	value: unknown,
};

/**  `ime_config_set` 的返回：失败项不让整批失败（`config.setItems` 的语义）。 */
export type ImeSetResult = {
	/**  有改动需要重启输入法才生效（FR-SET-01 的重启横幅） */
	needs_restart: boolean,
	applied: number,
	skipped: ImeSkipped[],
};

/**  被核心跳过的一项（未登记、类型或取值不对……），`reason` 是核心给的原因。 */
export type ImeSkipped = {
	key: string,
	reason: string,
};

export type JevInput = {
	base_url: string,
	api_key: string | null,
	/**  为 `null` 时用 `jev-latest` */
	model: string | null,
};

export type JevView = {
	base_url: string,
	/**  例如 `••••a1b2`；没有密钥时为 `null` */
	key_tail: string | null,
	model: string,
};

/**  一封周信。时间戳是 Unix 毫秒（前端绑定不导出 i64）。 */
export type LetterItem = {
	id: number,
	/**  那周的周一，`YYYY-MM-DD` */
	week_start: string,
	content: string,
	/**  为真时信末显示 `AI 生成` 标签；本地模板写的不加 */
	ai_generated: boolean,
	read: boolean,
	created_ts: number,
};

/**
 *  `letter:new`：晴晴写好了这周的周信（FR-REV-02，ADR 0030）。卡片层提示“晴晴给你写了一封信”，点开后用
 *  `letters_list` 取正文；`ai_generated` 时信末加 `AI 生成` 标签，模板信不加。
 */
export type LetterNew = {
	/**  `letter` 表的行号 */
	id: number,
	/**  那周的周一，`YYYY-MM-DD` */
	week_start: string,
	ai_generated: boolean,
};

export type LlmInput = {
	base_url: string,
	api_key: string | null,
	/**  按优先级排列；为空时用默认模型 */
	models: string[],
};

export type LlmView = {
	base_url: string,
	key_tail: string | null,
	/**  按优先级排列 */
	models: string[],
};

export type MemoryItem = {
	id: number,
	content: string,
	created_ts: number,
};

/**  “测试连接”里一个模型的结果（FR-AIG-04 第 4 条）。 */
export type ModelProbeView = {
	model: string,
	ok: boolean,
	latency_ms: number,
	/**  `ok`、HTTP 状态码或 `timeout` / `network` 等错误类别 */
	status: string,
};

export type ModelStatusView = {
	model: string,
	available: boolean,
	breaker_open: boolean,
	/**  最近 20 次调用的成功率（0～1）；没有调用时为空。 */
	success_rate: number | null,
	p50_ms: number | null,
};

/**  显示状态（04 第 3.1 节；`typo` 是瞬时事件，不作为显示状态下发）。 */
export type MoodState = "fluent" | "hesitant" | "low" | "agitated" | "tired" | "unknown";

/**
 *  `mood:typo`：刚打错了字（04 FR-STA-04 的 `typo` 瞬时事件）。小精灵“晃一下”（DS-MOTION-02），天气不变（FR-WGT-03）。
 *  最多每 [`crate::pulse::TYPO_MIN_GAP_MS`] 推一次，动画不会连成闪烁（DS-MOTION-04）。ADR 0036。
 */
export type MoodTypo = Record<string, never>;

/**  设置页展示的出网记录；只包含接口、模型、字段名和计量信息，不含请求或响应正文。 */
export type NetLogView = {
	/**  Unix 毫秒；前端用 number 展示即可，时间不会超过 JavaScript 安全整数范围。 */
	ts: number,
	api: string,
	model: string | null,
	fields: string[],
	latency_ms: number | null,
	status: string,
	tokens_in: number | null,
	tokens_out: number | null,
};

/**  一次按键。 */
export type Pulse = {
	/**  Hub 收到这一键的时刻（Unix 毫秒） */
	ts: number,
	/**  离上一键多久（毫秒，最多 [`MAX_IKI_MS`]）；会话里的第一键为 0 */
	iki_ms: number,
	/**  退格或删除：成串的在心电图上标红 */
	backspace: boolean,
};

/**
 *  `reminder:due`：日程或待办到点（FR-SCH-07、FR-SCH-14），卡片层显示 `title` / `body` 和“知道了 / 5 分钟后 / 10 分钟后”
 *  （`todo_digest` 只有“知道了”），按钮调 `reminder_action(id, …)`。`kind`：`schedule` / `deadline` / `all_day` /
 *  `todo` / `todo_eve`（截止前一天晚上，只在小组件）/ `todo_digest`。系统通知由后端另弹。
 */
export type ReminderDue = {
	id: number,
	kind: string,
	/**  日程或待办的行号；汇总为 0 */
	ref_id: number,
	title: string,
	body: string,
};

/**  `reminder:missed`：Hub 启动时发现 12 小时内错过的提醒，以“错过的提醒”卡片集中展示一次（FR-SCH-07）。 */
export type ReminderMissed = {
	title: string,
	body: string,
	items: ReminderDue[],
};

/**
 *  `research:invite`：研究模式的定时自评邀请（FR-DMO-04）。小组件弹出“主动报告心情”面板，可跳过（`research_dismiss`）；
 *  `answer_until_ts`（Unix 毫秒）之前提交的自评记为研究数据（`source = esm`），过了就按普通自评记。
 */
export type ResearchInvite = {
	answer_until_ts: number,
};

/**  用户对提醒卡片的操作（FR-RST-06 第 2 条），也是 `reminder_log.action` 的取值。 */
export type RestAction = 
/**  已完成（喝水卡片上叫“喝了”） */
"done" | 
/**  5 分钟后 */
"later" | 
/**  今天不再提醒 */
"today_off";

/**
 *  `rest:due`：该休息了（FR-RST-06）。小组件显示提醒卡片和 `已完成` / `5 分钟后` / `今天不再提醒`，
 *  用户的选择经 `rest_action` 交回后端。`tired` 时护眼卡片换文案“打了很久啦，眼睛也累了吧”（FR-RST-07）。
 */
export type RestDue = {
	kind: RestKind,
	tired: boolean,
};

/**  四类提醒，声明顺序即优先级（高 → 低）。 */
export type RestKind = "night" | "move" | "eye" | "water";

/**
 *  `review:evening`：晚间小结（FR-REV-01）。小组件卡片层显示（FR-WGT-07）：统计、天气色带和一句本地模板（不加 AI 标识）；
 *  卡片上的“看看今天的看板”打开看板，“今天不用了”只收起卡片（同一天不会再出）。
 */
export type ReviewEvening = EveningSummary;

/**  作息洞察（FR-REV-03）：最近若干晚的停止打字时间、平均停止时间、熬夜天数。 */
export type Routine = {
	/**  从早到晚，每晚一项（含没有记录的晚上），最后一项是最近一个已经结束的晚上 */
	nights: RoutineNight[],
	/**  有记录的晚上的平均停止时间，单位同 `stop_min`，四舍五入到分钟；一晚都没有时为 `null` */
	avg_stop_min: number | null,
	/**  熬夜天数 */
	late_nights: number,
	/**  有记录的晚数 */
	counted_nights: number,
};

/**  一晚的停止打字时间（`get_routine` 的折线点）。 */
export type RoutineNight = {
	/**  当晚日期，本地 `YYYY-MM-DD` */
	date: string,
	/**  停止打字时间，Unix 毫秒；这晚 18:00 后没有在这台电脑上打字时为 `null` */
	stop_ts: number | null,
	/**  停止打字时间距当晚日期 0 点的分钟数（18:00 = 1080，次日 01:30 = 1530），折线的纵轴 */
	stop_min: number | null,
	/**  晚于 00:00 */
	late: boolean,
};

/**  会话的安全状态，存在 `chat_session.safe_mode`（ADR 0018 第 3 条）。 */
export type SafeMode = 
/**  普通模式 */
"off" | 
/**  触发过危机识别：用 P-CHAT-SAFE，求助卡片固定在窗口顶部（FR-SAF-02/03） */
"on" | 
/**  用户点了“我说的不是这个意思”：回到普通模式、词表阈值提高，求助信息仍折叠显示一行（FR-SAF-06） */
"dismissed";

/**
 *  `safety:invite`：改写时原文命中危机词表（FR-RWR-05 第 3 条，ADR 0028 第 4 条）。核心已退出改写模式并在光标旁
 *  显示气泡；界面在小组件一句话区给出最高优先级的求助入口（`rewrite.crisis_bubble`），点了打开对话并显示求助卡片。
 *  不自动弹出对话窗口：用户正在别的应用里打字。
 */
export type SafetyInvite = {
	source: SafetyInviteSource,
};

/**  `safety:invite` 的来源。目前只有温柔改写。 */
export type SafetyInviteSource = "rewrite";

/**
 *  `safety:triggered`：危机识别命中（FR-SAF-01）。对话窗口立即在顶部固定显示求助卡片（FR-SAF-02），
 *  本会话切换为安全模式。
 */
export type SafetyTriggered = {
	session_id: number,
};

/**  `schedule:detected`：L2 确认是日程（FR-SCH-05 第 2 条），卡片层先显示“识别中…”；字段随后经 `schedule:ready` 填入。 */
export type ScheduleDetected = {
	card_id: number,
};

/**  新建或修改日程时填的字段（卡片上的“修改”、日程页的新建与编辑）。 */
export type ScheduleInput = {
	/**  ≤ 12 字 */
	title: string,
	date: string | null,
	time: string | null,
	end_time: string | null,
	all_day: boolean,
	location: string | null,
	is_deadline: boolean,
	/**  提前几秒提醒；为空时按类型给默认值（有时刻的用设置 `sch.default_offsets`，截止类 1 天 + 2 小时，全天当天 09:00） */
	remind_offsets: number[] | null,
};

/**  一条日程（09 D-12）。时间戳是 Unix 毫秒（前端绑定不导出 i64）。 */
export type ScheduleItem = {
	id: number,
	/**  已忽略的只留哈希，标题等为 `null` */
	title: string | null,
	/**  `YYYY-MM-DD` */
	date: string | null,
	/**  `HH:MM`；全天日程为 `null` */
	time: string | null,
	end_time: string | null,
	all_day: boolean,
	location: string | null,
	is_deadline: boolean,
	/**  提前几秒提醒（FR-SCH-07）；全天日程固定当天 09:00，为空数组 */
	remind_offsets: number[],
	/**  `pending` 待确认 / `added` 已添加 / `ignored` 已忽略 */
	status: string,
	/**  `ai`（卡片显示 `AI 识别`）/ `manual` */
	source: string,
	/**
	 *  `adjusted` 日期以代码为准、`maybe_past` 时间可能已过、`confirm_date` 请确认日期、`need_time` 请补充时刻、
	 *  `local` 本地规则抽取（请确认信息）、`maybe_dup` 可能已经添加过
	 */
	flags: string[],
	created_ts: number,
};

/**
 *  `schedule:ready`：抽取完成，已存为待确认。`schedule` 为 `null` 表示 24 小时内已经提示过同一件事（FR-SCH-06），
 *  卡片直接收起。卡片显示 `AI 识别`；`flags` 含 `local` 时标注“请确认信息”，含 `maybe_dup` 时提示“可能已经添加过”；
 *  `conflicts` 非空时加一行“⚠ 与「…」时间重叠”（FR-SCH-11）。按钮调 `schedule_confirm` / `schedule_update` / `schedule_ignore`；
 *  60 秒无操作收起，留在待确认列表里。
 */
export type ScheduleReady = {
	card_id: number,
	schedule: ScheduleItem | null,
	conflicts: ConflictItem[],
};

/**  新建或修改日程的结果：行号与时间重叠的日程（只提示，不阻止，FR-SCH-11 第 3 条）。 */
export type ScheduleSaved = {
	id: number,
	conflicts: ConflictItem[],
};

/**  状态时间线上的一段（FR-DSH-02）：相邻、同状态、间隔不超过 [`TIMELINE_GAP_MS`] 的记录合并成一段。 */
export type Segment = {
	/**  Unix 毫秒 */
	start_ts: number,
	end_ts: number,
	state: MoodState,
	/**  这一段最后一条状态记录的行号：点开时用 `state_explain(mood_id)` 取那一刻的解释（FR-STA-09） */
	mood_id: number,
};

/**
 *  `self_report:changed`：用户刚自评（FR-STA-10）。到 `until_ts` 之前小组件显示“你说的：…”；
 *  “说不上来”时 `until_ts` 就是自评时刻，即不覆盖显示。
 */
export type SelfReportChanged = {
	weather: SelfWeather,
	/**  Unix 毫秒（前端绑定不导出 i64，毫秒时间戳在 f64 中是精确的） */
	until_ts: number,
};

/**  `self_report_list` 的一行（10 第 5.1 节）。 */
export type SelfReportItem = {
	id: number,
	/**  Unix 毫秒。用 f64 是因为前端绑定不导出 i64，毫秒时间戳在 f64 中是精确的。 */
	ts: number,
	weather: SelfWeather,
	/**  只存本地（NFR-PRI-09） */
	note: string | null,
	/**  同一时刻的自动判断 */
	auto_state: MoodState | null,
};

/**  自评选项（`self_report.weather`）。 */
export type SelfWeather = 
/**  ☀️ 挺好 */
"sunny" | 
/**  ⛅ 有点犹豫 */
"cloudy" | 
/**  🌧 有点低落 */
"rain" | 
/**  ⛈ 有点烦 */
"storm" | 
/**  🌙 有点累 */
"night" | 
/**  🤷 说不上来 */
"unsure";

/**  `settings_schema` 的一项（ADR 0019 第 9 条）：设置页按它出控件、设范围、写提示，不在前端另抄一份取值范围。 */
export type SettingField = {
	key: string,
	kind: SettingFieldKind,
	default: SettingValue,
};

/**  取值范围（[`Kind`] 的可序列化形态），按 `type` 区分。 */
export type SettingFieldKind = { type: "bool" } | 
/**  闭区间 */
{ type: "number"; min: number | null; max: number | null } | 
/**  闭区间内的整数 */
{ type: "int"; min: number | null; max: number | null } | 
/**  枚举字符串 */
{ type: "choice"; options: string[] } | 
/**  一段文字，格式见 `item` */
{ type: "text"; item: SettingItem } | 
/**  字符串列表：最多 `max_items` 项，每项格式见 `item`，不许重复（忽略 ASCII 大小写） */
{ type: "list"; item: SettingItem; max_items: number };

/**
 *  文字类设置的格式。只放已知格式，不收任意文本：设置值会出现在界面和固定文案里（求助卡片），
 *  任意文本绕得过禁用词校验（ADR 0019 第 3 条）。
 */
export type SettingItem = 
/**  进程名，如 `Zoom.exe`（[`dnd::valid_app`]） */
"app" | 
/**  时段 `"HH:MM-HH:MM"`，可跨午夜（[`dnd::QuietRange`]） */
"time_range" | 
/**  电话号码：数字、空格与 `+-()`，至少 3 个数字，不超过 [`PHONE_MAX_CHARS`] 字；空串表示没填 */
"phone" | 
/**
 *  用户研究的匿名编号（FR-DMO-04、12 第 4 节）：ASCII 字母、数字、`-`、`_`，不超过
 *  [`RESEARCH_ID_MAX_CHARS`] 字；空串表示没填
 */
"research_id" | 
/**  Hub 的全局快捷键（FR-ENT-04），如 `ctrl+alt+q`；空串表示不设（[`super::hotkey::accepts`]，ADR 0036） */
"hotkey";

/**  设置项的值。只有这四种形态，对应 [`Kind`]；以 JSON 文本落库（`true` / `0.8` / `"system"` / `["22:00-07:00"]`）。 */
export type SettingValue = boolean | number | string | string[];

/**  `settings:changed`：只带键名，窗口自行重新读取。 */
export type SettingsChanged = {
	key: string,
};

/**  一条说明。`value` 是文案变量（{p} 百分比、{n} 次数、{m} 分钟）的值。 */
export type Signal = {
	kind: SignalKind,
	value: number | null,
};

/**  说明种类，序列化名就是 `explain.toml` 中 `[signal.*]` 的键。 */
export type SignalKind = 
/**  `kpm_z ≤ -1`，值为 {p} */
"kpm_slow" | 
/**  `kpm_z ≥ 1`，值为 {p} */
"kpm_fast" | 
/**  `iki_med_z ≥ 1` */
"iki_long" | 
/**  `iki_iqr_z ≥ 1.5` */
"iki_messy" | 
/**  `pause_cnt ≥ 2`，值为 {n} */
"pause" | 
/**  `abandon = true` */
"abandon" | 
/**  `delete_committed ≥ 5`，值为 {n} */
"delete_committed" | 
/**  `bs_rate_z ≥ 1` */
"bs_more" | 
/**  `typo_cnt ≥ 2`，值为 {n} */
"typo" | 
/**  `page_flips ≥ 3`，值为 {n} */
"page_flips" | 
/**  `session_min ≥ 45`，值为 {m} */
"session" | 
/**  R5 命中 */
"late";

/**  状态分布的一项（环形图）：这个状态有多少个窗口。 */
export type StateCount = {
	state: MoodState,
	windows: number,
};

/**  `status:changed`：载荷同 `get_status`。 */
export type StatusChanged = StatusSnapshot;

/**  `get_status` 的返回值，也是 `status:changed` 事件的载荷。 */
export type StatusSnapshot = {
	state: MoodState,
	weather: Weather,
	/**  当前状态的可能性 0–1；冷启动或只有本地规则时为 `None`，界面不显示百分比。 */
	prob: number | null,
	/**  AI 网关降级为离线模式（FR-AIG-05），小组件显示“离线”角标。 */
	offline: boolean,
	/**  无痕 / 密码框 / 黑名单应用，或用户暂停感知。 */
	paused: boolean,
	/**  与输入法核心的 XQP 连接是否已握手。 */
	connected: boolean,
	/**  基线建立进度 0–100（FR-STA-03 冷启动）。 */
	baseline_progress: number,
};

/**  `todo:detected`：L2 确认是待办（FR-SCH-13），卡片层先显示“识别中…”。 */
export type TodoDetected = {
	card_id: number,
};

/**  新建或修改待办时填的字段。 */
export type TodoInput = {
	/**  ≤ 16 字 */
	title: string,
	due_date: string | null,
};

/**  一件待办（09 D-25）。 */
export type TodoItem = {
	id: number,
	title: string | null,
	due_date: string | null,
	/**  `pending` 待确认 / `open` 未完成 / `done` 已完成 / `archived` 已归档 / `ignored` 已忽略 */
	status: string,
	source: string,
	created_ts: number,
	done_ts: number | null,
};

/**
 *  `todo:ready`：抽取完成，已存为待确认；`todo` 为 `null` 表示 24 小时内已经提示过，卡片收起。
 *  按钮调 `todo_confirm` / `todo_update` / `todo_ignore`。
 */
export type TodoReady = {
	card_id: number,
	todo: TodoItem | null,
};

/**
 *  `typing:pulse`：最近 100 毫秒内的按键脉冲（打字心电图，FR-DSH-02、FR-DMO-03）。只有键间间隔和是不是退格，
 *  不含键值与文字；只在看板窗口看得见时推送，最多每秒 10 次。ADR 0036。
 */
export type TypingPulse = {
	keys: Pulse[],
};

export type UiError = {
	/**  稳定的错误码，前端可据此分支；只写日志，不展示给用户 */
	code: string,
	/**  `hub_templates/ui_copy.toml` 里的文案键，前端据此显示提示 */
	message_key: string,
};

/**  今日用量的一行（FR-AIG-07、FR-SET-08）。 */
export type UsageRow = {
	kind: BudgetKind,
	used: number,
	cap: number,
};

/**  “准 / 不准”（`feedback.verdict`）。 */
export type Verdict = "fit" | "unfit";

/**  情绪天气（04 第 3.1 节、07 DS-COLOR）。`Wind` 只用于打错字的瞬时动画，不作为持续状态。 */
export type Weather = "sunny" | "wind" | "cloudy" | "rain" | "storm" | "night";

/**  周报里的一天（每日输入时长柱状图、休息与饮水、专注）。 */
export type WeekDay = {
	date: string,
	typing_min: number,
	rests_due: number,
	rests_done: number,
	water: number,
	focus_min: number,
};

/**  周报（FR-DSH-04）。作息洞察另用 `get_routine`。 */
export type WeekReport = {
	/**  那周的周一 */
	week_start: string,
	/**  周一到周日 */
	days: WeekDay[],
	/**  状态分布，按固定顺序，只列出现过的 */
	states: StateCount[],
	/**  7 × 24：周一到周日 × 0–23 时，“低落 / 疲劳”出现的窗口数（热力图） */
	heat: number[][],
	/**  休息完成率（百分比，四舍五入）；这周没出过提醒时为空 */
	rest_rate: number | null,
	rests_done: number,
	rests_due: number,
	water: number,
	/**  本周新加入的日程（已添加的，按创建时间）与完成的待办 */
	schedules_added: number,
	todos_done: number,
	focus_min: number,
	/**  一句话总结（`weekly_line.toml`，本地模板） */
	line: string,
};

/**
 *  `open_window` 与 `--open` 的目标。标签与 `tauri.conf.json` 的窗口 `label`、
 *  前端 `src/windows/<label>/` 目录一一对应。
 */
export type WindowTarget = "widget" | "chat" | "dashboard" | "settings" | "onboarding";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

